// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

// 为某个枚举单独设置错误码
func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsInvalidParam(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAM.String() && e.Code == 400
}

func ErrorInvalidParam(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAM.String(), fmt.Sprintf(format, args...))
}

func IsHorizontalPrivilegeEscalation(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_HorizontalPrivilegeEscalation.String() && e.Code == 403
}

func ErrorHorizontalPrivilegeEscalation(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_HorizontalPrivilegeEscalation.String(), fmt.Sprintf(format, args...))
}

func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 409
}

func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

func IsReviewHasReply(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ReviewHasReply.String() && e.Code == 409
}

func ErrorReviewHasReply(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_ReviewHasReply.String(), fmt.Sprintf(format, args...))
}
